@startuml
actor Propietario

boundary "Interfaz de Pedidos"
control "Gestor de Pedidos"
entity "Base de Datos de Pedidos"

Propietario -> "Interfaz de Pedidos": SeleccionarPedidosRecibidos()
"Interfaz de Pedidos" -> "Gestor de Pedidos": ObtenerPedidosRecibidos()
"Gestor de Pedidos" -> "Base de Datos de Pedidos": ConsultarPedidosRecibidos()
"Base de Datos de Pedidos" --> "Gestor de Pedidos": PedidosRecibidos
"Gestor de Pedidos" -> "Interfaz de Pedidos": MostrarPedidosRecibidos(PedidosRecibidos)
Propietario -> "Interfaz de Pedidos": SeleccionarPedido(pedido)
"Interfaz de Pedidos" -> "Gestor de Pedidos": ObtenerDetallePedido(pedido)
"Gestor de Pedidos" -> "Base de Datos de Pedidos": ConsultarDetallePedido(pedido)
"Base de Datos de Pedidos" --> "Gestor de Pedidos": DetallePedido
"Gestor de Pedidos" -> "Interfaz de Pedidos": MostrarDetallePedido(DetallePedido)
Propietario -> "Interfaz de Pedidos": AceptarPedido(pedido)
"Interfaz de Pedidos" -> "Gestor de Pedidos": ActualizarEstadoPedido(pedido, aceptado)
"Gestor de Pedidos" -> "Base de Datos de Pedidos": ActualizarEstadoPedido(pedido, aceptado)
"Gestor de Pedidos" -> "Interfaz de Pedidos": ConfirmarAceptacionPedido()

alt Propietario puede realizar el pedido
    "Interfaz de Pedidos" -> "Gestor de Pedidos": VerificarDisponibilidad(pedido)
    "Gestor de Pedidos" -> "Base de Datos de Pedidos": ConsultarDisponibilidad(pedido)
    "Base de Datos de Pedidos" --> "Gestor de Pedidos": Disponibilidad
else Propietario no puede realizar el pedido
    "Interfaz de Pedidos" -> "Base de Datos de Pedidos": Devolucion()
 
    "Base de Datos de Pedidos" --> "Interfaz de Pedidos": return
end

@enduml