@startuml

actor Usuario
boundary "Interfaz Usuario"
control "Gestor Usuario"
entity "Datos Usuario"

Usuario -> "Interfaz Usuario": VerDetallesCuenta()
"Interfaz Usuario" -> "Gestor Usuario": ObtenerDetallesCuenta()
"Gestor Usuario" -> "Datos Usuario": ConsultarDetallesCuenta()
"Datos Usuario" --> "Gestor Usuario": DetallesCuenta
"Gestor Usuario" -> "Interfaz Usuario": MostrarDetallesCuenta(DetallesCuenta)
Usuario -> "Interfaz Usuario": SeleccionarOpcionModificarDetalles()
"Interfaz Usuario" -> "Gestor Usuario": ObtenerDetallesModificar()
"Gestor Usuario" -> "Interfaz Usuario": MostrarDetallesModificar(DetallesModificar)
Usuario -> "Interfaz Usuario": SeleccionarDetallesModificar(DetallesModificar)
"Interfaz Usuario" -> "Gestor Usuario": ConfirmarModificacionDetalles(DetallesModificar)
"Gestor Usuario" -> "Datos Usuario": ModificarDetalles(DetallesModificar)
"Gestor Usuario" -> "Interfaz Usuario": ConfirmarModificacion()

@enduml
