@startuml

actor "Proveedor de anuncios"
boundary "Interfaz Ofertas"
control "Gestor Ofertas"
entity DatosCliente

"Proveedor de anuncios" -> "Interfaz Ofertas": Generar_anuncios()
"Interfaz Ofertas" -> "Gestor Ofertas": Obtener_datos()
"Gestor Ofertas" -> DatosCliente: Obtener_datos()
DatosCliente --> "Gestor Ofertas": <<return>>
"Gestor Ofertas" -> "Interfaz Ofertas": Mostrar_anuncios()

@enduml
