/'
Seleccionar la opción de ver estado del pedido
Obtener los datos actuales del pedido
Mostrar estado del pedido
Actualizar a tiempo real la ubicación del pedido
'/
@startuml Ver estado pedido
actor "Cliente/Propietario"
boundary "Interfaz Pedido"
boundary "Interfaz Transportista"
control "Gestor Pedidos"

par transportista
    ref over "Interfaz Transportista": Actualizar_GPS()
    else cliente
    "Cliente/Propietario"->"Interfaz Pedido": Ver_Estado_Pedido()
    loop Error==false && Finalizado==false
        "Interfaz Pedido" -> "Gestor Pedidos": Solicitar_Estado_Actual()
        alt Solicitud Válida
            "Gestor Pedidos" --> "Interfaz Pedido": Actualizar_Estado_Pedido()
            "Interfaz Pedido" -> "Interfaz Pedido": Esperar_Un_Segundo()
        else Solicitud Invalida
            "Gestor Pedidos" --> "Interfaz Pedido": Mostrar_Error()
        end
    end
end
@enduml
