name: Generate PDFs

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      contents: write

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: cd ./others/tools && npm i && npm run generate && npm run merge
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: 'documents/*.pdf'
          commit_message: 'Regenerated PDF'